name: flutter_provider_boilerplate
description: "Flutter boilerplate project with provider state management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.8
  http: ^1.2.1
  intl: ^0.18.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt/Prompt-Medium.ttf
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
