name: flutter_provider_boilerplate
description: "Flutter boilerplate project with provider state management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

assets:
  - assets/images/
  - assets/logos/
  - assets/icons/

# uncomment when use fonts 
# fonts:
#   - family: Prompt
#     fonts:
#       - asset: assets/fonts/Prompt/Prompt-Bold.ttf
#       - asset: assets/fonts/Prompt/Prompt-Medium.ttf
#       - asset: assets/fonts/Prompt/Prompt-Regular.ttf
